### PR TITLE
add jupyterlab python package

### PR DESCRIPTION
**Pull request by bryanpaget**
Add jupyterlab python package.

### CODE REVIEW

**Review by Jose-Matsuda — DISMISSED** [review]

**Comment by Jose-Matsuda** [comment]
Just adding context; this issue broke both branches;
related commit to 2.0 branch is: https://github.com/StatCan/aaw-kubeflow-containers/commit/9b5fcc27d2ea3adbfa3f5339d63f58337f3ed687

image

**Comment by Souheil-Yazji** [comment]
I thought this package was in the base images we use? see 
https://github.com/jupyter/docker-stacks/blob/main/images/base-notebook/Dockerfile#L42

**Comment by bryanpaget** [comment]
> I thought this package was in the base images we use? see https://github.com/jupyter/docker-stacks/blob/main/images/base-notebook/Dockerfile#L42

I know! A new version was released May 06, which is the day our builds broke:

image

Further investigation may be required to truly understand how this broke our builds.

**Comment by bryanpaget** [comment]
I can confirm this issue has nothing to do with the upstream Docker images as I am able to build:
- https://github.com/jupyter/docker-stacks/blob/main/images/base-notebook/Dockerfile#L42
I am also able to build the refactored JupyterLab image:
- https://github.com/StatCan/aaw-kubeflow-containers/blob/images-refactoring/dockerfiles/jupyterlab/Dockerfile

**Comment by bryanpaget** [comment]
This is for main and no longer an issue.

**Pull request closed without merging**
